name: 构建SM8550内核-KernelSU-Next-SUS 
 
on:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 8192
        temp-reserve-mb: 2048 
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
 
    - name: Configure Git
      run: |
        git config --global user.name  "yuanqiongyoukong"
        git config --global user.email  "413722718@qq.com" 
 
    - name: 安装编译环境
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install ccache curl git repo python3 python-is-python3 -y
 
    - name: 拉取oneplus 12r内核清单
      run: |
        mkdir -p kernel && cd kernel
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git  -b oneplus/sm8550 -m oneplus_12r_v.xml  --depth=1
        repo sync -j$(nproc --all)
 
    - name: 添加KernelSU Next
      run: |
        cd kernel/kernel_platform/common
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh"  | bash -s next
 
    - name: 添加SUSFS
      run: |
        cd kernel
        git clone https://gitlab.com/simonpunk/susfs4ksu.git  -b gki-android13-5.15
        git clone https://github.com/TheWildJames/kernel_patches.git 
        cd kernel_platform 
        cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch  ./common/KernelSU-Next/
        cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch  ./common/
        cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
 
        # Apply patches 
        cd ./common/KernelSU-Next
        patch -p1 --forward < 10_enable_susfs_for_ksu.patch  || true
        cd ..
        patch -p1 < 50_add_susfs_in_gki-android13-5.15.patch  || true 
        cp ../../kernel_patches/69_hide_stuff.patch  ./
        patch -p1 -F 3 < 69_hide_stuff.patch 
        cp ../../kernel_patches/apk_sign.c_fix.patch  ./
        patch -p1 -F 3 < apk_sign.c_fix.patch 
        cp ../../kernel_patches/core_hook.c_fix.patch  ./
        patch -p1 --fuzz=3 < ./core_hook.c_fix.patch 
        cp ../../kernel_patches/selinux.c_fix.patch  ./
        patch -p1 -F 3 < selinux.c_fix.patch 
 
    - name: 修改内核构建脚本
      run: |
        cd kernel/kernel_platform/oplus/build
        sed -i '203a\export LTO=thin' oplus_setup.sh 
 
    - name: 编译内核
      run: |
        cd kernel
        export LTO=thin 
        ./kernel_platform/oplus/build/oplus_build_kernel.sh  kalama gki
 
    - name: Upload Image 
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU_Next-SUSFS
        path: kernel/out/dist/Image
